!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Shimon Panfil: Industrial Physics and Simulations                   !!
! http://industrialphys.com                                           !!
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK           !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODULE LBEM
USE TSURF
IMPLICIT NONE
PUBLIC
INTEGER::NS ! NUMBER OF SURFACES
INTEGER,PARAMETER::MAXNS=2 ! MAXIMUM NUMBER OF SURFACES
TYPE(TSURF_TYPE),ALLOCATABLE,DIMENSION(:)::SRF !(NS) SURFACES
INTEGER::NU ! NUMBER OF UNKNOWNS AND CONTROL POINTS
! Large arrays 
REAL(F64),ALLOCATABLE,DIMENSION(:,:)::LM !(NU,NU)
REAL(F64),ALLOCATABLE,DIMENSION(:)::QTOT !(NU)
REAL(F64),ALLOCATABLE,DIMENSION(:)::E !(NU)
REAL(F32),ALLOCATABLE,DIMENSION(:,:)::CP !(3,NU)
REAL(F64),ALLOCATABLE,DIMENSION(:)::xpot !(NU)
! Small arrays
REAL(F64)::SM(MAXNS,MAXNS),SMRH(MAXNS),PHI(MAXNS)
INTEGER::ENDSRF(MAXNS) !(NS)
CONTAINS
! CALLED WHEN SRF INITIALIZED
SUBROUTINE INIT_LBEM(FLAG)
    INTEGER::FLAG
    INTEGER::J
    NU=0
    DO J=1,NS
        STRT(J)=NU
        NU=NU+SRF(J)%NT
    ENDDO
    ALLOCATE(LM(NU,NU),QTOT(NU),XPOT(NU),CP(3,NU),E(NU),STAT=FLAG)
    IF(FLAG/=0) RETURN
    DO J=1,NS
        CALL LBEM_MK_QTOT0(SRF(J),STRT(J))
    ENDDO
    DO J=1,NS
        CALL LBEM_MK_CNTR(SRF(J),STRT(J))
    ENDDO
    DO J=1,NS
        CALL LBEM_MK_MAT1(SRF(J),STRT(J))
    ENDDO
    DO J=1,NU
        E(J)=ONE_F64
    ENDDO
    CALL GAUSS_JORDAN(LM,NU,E,1)


ENDSUBROUTINE INIT_LBEM
SUBROUTINE CLEAN_LBEM()
    IF(ALLOCATED(LM)) DEALLOCATE(LM)
    IF(ALLOCATED(QTOT)) DEALLOCATE(QTOT)
    IF(ALLOCATED(XPOT)) DEALLOCATE(XPOT)
    IF(ALLOCATED(CP)) DEALLOCATE(CP)
    IF(ALLOCATED(E)) DEALLOCATE(E)
ENDSUBROUTINE CLEAN_LBEM

! CONSTANT CHARGES
SUBROUTINE LBEM_MK_QTOT0(S,T0)
    TYPE(TSURF_TYPE):: S
    INTEGER ::T0
    INTEGER::I,V1,V2,V3
    REAL(F32)::A,B(3),C(3),W(3)
    DO I=1,S%NT 
        V1=S%TVEC(1,I)
        V2=S%TVEC(2,I)
        V3=S%TVEC(3,I)
        B=S%VVEC(:,V2)-S%VVEC(:,V1)
        C=S%VVEC(:,V3)-S%VVEC(:,V1)
        W=CROSS_F32(B,C)
        A=HALF_F32*SQRT(DOT_F32(W,W))
        QTOT(T0+I)=A
    ENDDO
ENDSUBROUTINE LBEM_MK_QTOT0

SUBROUTINE LBEM_MK_CNTR(S,T0)
    TYPE(TSURF_TYPE):: S
    INTEGER::T0
    INTEGER::I,V1,V2,V3
    DO I=1,S%NT 
        V1=S%TVEC(1,I)
        V2=S%TVEC(2,I)
        V3=S%TVEC(3,I)
        CP(:,I+T0)=THIRD_F32*(S%VVEC(:,V1)+S%VVEC(:,V2)+S%VVEC(:,V3))
    ENDDO
ENDSUBROUTINE LBEM_MK_CNTR

SUBROUTINE LBEM_MK_MAT1(S,k)
    TYPE(TSURF_TYPE):: S
    INTEGER k
    REAL(F64)::LPL_GF_TSURF1
    EXTERNAL  LPL_GF_TSURF1
    INTEGER::I,J
    DO I=1,S%NT
        DO J=1,NU ! CONTROL POINT               
                LM(J,I+K)=LPL_GF_TSURF1(S,CP(:,J),I)
        ENDDO
    ENDDO
ENDSUBROUTINE LBEM_MK_MAT1

ENDMODULE LBEM
