!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Shimon Panfil: Industrial Physics and Simulations        !
! http://industrialphys.com                                !
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION LPL_GF_TRG(TRG,DST) RESULT (RES)
    USE  LPL_GF_PINT
    IMPLICIT NONE
    REAL(F32)::TRG(3,3),DST(3)
    REAL(F64)::RES
    RES=POT_TRG(GET_TRGV(TRG),DST-TRG(:,1))
ENDFUNCTION LPL_GF_TRG


FUNCTION LPL_GF_TSURF1(TS,DST,T) RESULT (RES)
    USE  TSURF
    IMPLICIT NONE
    TYPE(TSURF_TYPE):: TS
    REAL(F32)::DST(3)
    INTEGER::T
    REAL(F64)::RES
    REAL(F32)::TRG(3,3) 
    REAL(F64)::LPL_GF_TRG
    EXTERNAL LPL_GF_TRG
    CALL GET_TRG(T)
    RES=LPL_GF_TRG(TRG,DST)
CONTAINS
SUBROUTINE GET_TRG(T)
    INTEGER::T
    TRG(:,1)=TS%VVEC(:,TS%TVEC(1,T))
    TRG(:,2)=TS%VVEC(:,TS%TVEC(2,T))
    TRG(:,3)=TS%VVEC(:,TS%TVEC(3,T))
ENDSUBROUTINE GET_TRG
ENDFUNCTION LPL_GF_TSURF1

FUNCTION LPL_GF_TSURF(TS,DST,CHRG) RESULT (RES)
    USE  TSURF
    IMPLICIT NONE
    TYPE(TSURF_TYPE):: TS
    REAL(F32)::DST(3)
    REAL(F64)::CHRG(:),RES
    REAL(F64)::LPL_GF_TSURF1
    EXTERNAL LPL_GF_TSURF1
    INTEGER::T
    RES=0.0D0
    DO T=1,TS%NT
        RES=RES+LPL_GF_TSURF1(TS,DST,T)*CHRG(T)
    ENDDO
CONTAINS
ENDFUNCTION LPL_GF_tsurf


FUNCTION LPL_GF_DISK(POS,DIR,RAD,DST) RESULT (RES)
    USE VEC3D
    IMPLICIT NONE
    REAL(F32)::POS(3),DIR(3),RAD,DST(3)    
    REAL(F64)::RES
    REAL(F64)::R,Z
    REAL(F32)::RV(3)
    RV=DST-POS
    Z=DOT_F32(RV,DIR)/LENGTH_F32(DIR)
    R=SQRT(DOT_F32(RV,RV)-Z**2)
    CALL DISK_POT(RES,R,Z,REAL(RAD,F64))
ENDFUNCTION LPL_GF_DISK

SUBROUTINE LPL_GF_CYL(RES,POS,DIR,RAD,LENGTH,DST) 
    USE VEC3D
    IMPLICIT NONE
    REAL(F32)::POS(3),DIR(3),RAD,DST(3),LENGTH    
    REAL(F64)::RES
    REAL(F64)::R,Z,res1,res2
    REAL(F32)::RV(3)
    RV=DST-POS
    Z=DOT_F32(RV,DIR)/LENGTH_F32(DIR)
    R=SQRT(DOT_F32(RV,RV)-Z**2)
    CALL DISK_POT(RES1,R,Z,REAL(RAD,F64))
    CALL DISK_POT(RES2,R,Z+LENGTH,REAL(RAD,F64))
    RES=res1-res2
ENDSUBROUTINE LPL_GF_CYL

SUBROUTINE GET_PSI(PSI,DST) ! EXTERNAL POTENTIAL
    USE CYL_MAG
    REAL(F64)::PSI
    REAL(F32)::DST(3)
    CALL LPL_GF_CYL(PSI,MAG_POS,MAG_DIR,MAG_R,MAG_H,DST)
    PSI=PSI*MAG_MZ*MAG_NORM
ENDSUBROUTINE GET_PSI

