!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Shimon Panfil: Industrial Physics and Simulations        !
! http://industrialphys.com                                !
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODULE LPL_GF_PINT
USE FDEFS
USE VEC3D
IMPLICIT NONE
PUBLIC
REAL(F64),PARAMETER::ZZERO=1.0D-12
CONTAINS
REAL(F64) FUNCTION FPSI(S,U,V,W2) 
    REAL(F64):: S,U,V,W2
    REAL(F64)::VV,DD,D,R,B,A,C
    VV=(1.0D0-V**2)
    DD=W2*VV-U**2
    D=SQRT(DD)
    R=SQRT(S**2+W2)
    B=R+V*S+U
    A=D*(R*V+S)
    C=DD+U*B
    FPSI= -S*VV+(S*VV-V*U)*LOG(B)-U*LOG(R-S)+D*ATAN2(A,C)
ENDFUNCTION FPSI  

! FPSI0(S,U,W)= FPSI(S,U,0,W) 
REAL(F64) FUNCTION FPSI0(S,U,W2)
    REAL(F64):: S,U,W2
    REAL(F64)::DD,D,R,B,A,C
    DD=W2-U**2
    D=SQRT(DD)
    R=SQRT(S**2+W2)
    B=R+U
    A=D*S
    C=DD+U*B
    FPSI0= -S+S*LOG(B)-U*LOG(R-S)+D*ATAN2(A,C)
ENDFUNCTION FPSI0

! TRIANGLE 

REAL(F64) FUNCTION POT_TRG1(A,P,H,X,Y,Z)
    REAL(F64)::A,P,H,X,Y,Z
    REAL(F64)::SR,SL,W2L,W2R,UL,UR,VL,VR,A1L,A2L,A1R,A2R,AL,BL,AR,BR,Z2
    Z2=Z**2
    IF(Z2<ZZERO) Z2=ZZERO
    AL=P/H;AR=(P-A)/H
    BL=AL*Y-X;BR=AR*Y-X+A
    A2R=1.0D0+AR*AR
    A1R=SQRT(A2R)
    A2L=1.0D0+AL*AL
    A1L=SQRT(A2L)
    SR=AR*BR/A2R-Y
    SL=AL*BL/A2L-Y
    W2R=Z2/A2R+BR*BR/(A2R*A2R)
    W2L=Z2/A2L+BL*BL/(A2L*A2L)
    VR=AR/A1R
    VL=AL/A1L;
    UR=BR/(A1R*A2R)
    UL=BL/(A1L*A2L)
    POT_TRG1= H*LOG(A1R/A1L)+(FPSI(SR+H,UR,VR,W2R)-FPSI(SR,UR,VR,W2R))*A2R+(FPSI(SL,UL,VL,W2L)-FPSI(SL+H,UL,VL,W2L))*A2L
ENDFUNCTION POT_TRG1

REAL(F64) FUNCTION POT_TRG(TRGV,DSTV)
    REAL(F32)::TRGV(3),DSTV(3)
    REAL(F64)::A,P,H,X,Y,Z2
    REAL(F64)::SR,SL,W2L,W2R,UL,UR,VL,VR,A1L,A2L,A1R,A2R,AL,BL,AR,BR
    A=TRGV(1);P=TRGV(2);H=TRGV(3)
    X=DSTV(1);Y=DSTV(2);Z2=DSTV(3)**2
    IF(Z2<ZZERO) Z2=ZZERO
    AL=P/H;AR=(P-A)/H
    BL=AL*Y-X;BR=AR*Y-X+A
    A2R=1.0D0+AR*AR
    A1R=SQRT(A2R)
    A2L=1.0D0+AL*AL
    A1L=SQRT(A2L)
    SR=AR*BR/A2R-Y
    SL=AL*BL/A2L-Y
    W2R=Z2/A2R+BR*BR/(A2R*A2R)
    W2L=Z2/A2L+BL*BL/(A2L*A2L)
    VR=AR/A1R
    VL=AL/A1L;
    UR=BR/(A1R*A2R)
    UL=BL/(A1L*A2L)
    POT_TRG= H*LOG(A1R/A1L)+(FPSI(SR+H,UR,VR,W2R)-FPSI(SR,UR,VR,W2R))*A2R+(FPSI(SL,UL,VL,W2L)-FPSI(SL+H,UL,VL,W2L))*A2L
ENDFUNCTION POT_TRG

! PARALLELOGRAM 
REAL(F64) FUNCTION POT_PAR(PARV,DSTV)
    REAL(F32)::PARV(3),DSTV(3)
    REAL(F64)::A,P,H,X,Y,Z2
    REAL(F64)::SR,SL,W2L,W2R,UL,UR,VL,A1L,A2L,AL,BL,BR
    A=PARV(1);P=PARV(2);H=PARV(3)
    X=DSTV(1);Y=DSTV(2);Z2=DSTV(3)**2
    IF(Z2<ZZERO) Z2=ZZERO
    AL=P/H
    BL=AL*Y-X;BR=BL+A
    A2L=1.0D0+AL*AL
    A1L=SQRT(A2L)
    SR=AL*BR/A2L-Y
    SL=AL*BL/A2L-Y
    W2R=Z2/A2L+BR*BR/(A2L*A2L)
    W2L=Z2/A2L+BL*BL/(A2L*A2L)
    VL=AL/A1L
    UR=BR/(A1L*A2L)
    UL=BL/(A1L*A2L)
    POT_PAR=(FPSI(SR+H,UR,VL,W2R)-FPSI(SR,UR,VL,W2R)+FPSI(SL,UL,VL,W2L)-FPSI(SL+H,UL,VL,W2L))*A2L;
ENDFUNCTION POT_PAR
 
! RECTANGULAR, P=0 
REAL(F64) FUNCTION POT_RECT(A,H,DSTV)
    REAL(F64)::A,H
    REAL(F32)::DSTV(3)
    REAL(F64)::X,Y,Z2,SR,SL,W2L,W2R,UL,UR,BL,BR
    X=DSTV(1);Y=DSTV(2);Z2=DSTV(3)**2
    IF(Z2<ZZERO) Z2=ZZERO
    BL=-X;BR=-X+A
    SR=-Y
    SL=-Y
    W2R=Z2+BR*BR
    W2L=Z2+BL*BL
    UR=BR
    UL=BL
    POT_RECT= FPSI0(SR+H,UR,W2R)-FPSI0(SR,UR,W2R)+FPSI0(SL,UL,W2L)-FPSI0(SL+H,UL,W2L);
ENDFUNCTION POT_RECT
ENDMODULE LPL_GF_PINT

