!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Shimon Panfil: Industrial Physics and Simulations        !
! http://industrialphys.com                                !
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION LPL_GF_TSURF1(TS,DST,T) RESULT (RES)
    USE  TSURF
    use LPL_GF_PINT
    IMPLICIT NONE
    TYPE(TSURF_TYPE):: TS
    REAL(F32)::DST(3)
    INTEGER::T
    REAL(F64)::RES
    REAL(F32)::R(3),U(3),V(3),K(3),N(3),M(3),R2
    REAL(F64)::A,P,H,X,Y,Z
  
    R=TS%VVEC(:,TS%TVEC(1,T))
    U=TS%VVEC(:,TS%TVEC(2,T))-R
    V=TS%VVEC(:,TS%TVEC(3,T))-R
    A=LENGTH_F32(U)
    K=U/A
    R2=DOT_F32(V,V)
    P=DOT_F32(V,K)
    H=SQRT(R2-P**2)
    M=(U-P*K)/H
    N=CROSS_F32(K,M)
    X=DOT_F32(DST-R,K)
    Y=DOT_F32(DST-R,M)
    Z=DOT_F32(DST-R,N)
    RES=POT_TRG1(A,P,H,X,Y,Z)
ENDFUNCTION LPL_GF_TSURF1

FUNCTION LPL_GF_TSURF(TS,DST,CHRG) RESULT (RES)
    USE  TSURF
    IMPLICIT NONE
    TYPE(TSURF_TYPE):: TS
    REAL(F32)::DST(3)
    REAL(F64)::CHRG(:),RES
    REAL(F64)::LPL_GF_TSURF1
    EXTERNAL LPL_GF_TSURF1
    INTEGER::T
    RES=0.0D0
    DO T=1,TS%NT
        RES=RES+LPL_GF_TSURF1(TS,DST,T)*CHRG(T)
    ENDDO
CONTAINS
ENDFUNCTION LPL_GF_tsurf


FUNCTION LPL_GF_DISK(POS,DIR,RAD,DST) RESULT (RES)
    USE VEC3D
    IMPLICIT NONE
    REAL(F32)::POS(3),DIR(3),RAD,DST(3)    
    REAL(F64)::RES
    REAL(F64)::R,Z
    REAL(F32)::RV(3)
    RV=DST-POS
    Z=DOT_F32(RV,DIR)/LENGTH_F32(DIR)
    R=SQRT(DOT_F32(RV,RV)-Z**2)
    CALL DISK_POT(RES,R,Z,REAL(RAD,F64))
ENDFUNCTION LPL_GF_DISK

SUBROUTINE LPL_GF_CYL(RES,POS,DIR,RAD,LENGTH,DST) 
    USE VEC3D
    IMPLICIT NONE
    REAL(F32)::POS(3),DIR(3),RAD,DST(3),LENGTH    
    REAL(F64)::RES
    REAL(F64)::R,Z,res1,res2
    REAL(F32)::RV(3)
    RV=DST-POS
    Z=DOT_F32(RV,DIR)/LENGTH_F32(DIR)
    R=SQRT(DOT_F32(RV,RV)-Z**2)
    CALL DISK_POT(RES1,R,Z,REAL(RAD,F64))
    CALL DISK_POT(RES2,R,Z+LENGTH,REAL(RAD,F64))
    RES=res1-res2
ENDSUBROUTINE LPL_GF_CYL

REAL(F64) function PSI(DST) ! EXTERNAL POTENTIAL
    USE CYL_MAG
    REAL(F32)::DST(3)
    CALL LPL_GF_CYL(PSI,MAG_POS,MAG_DIR,MAG_R,MAG_H,DST)
ENDfunction PSI

