########################################################################
# Shimon Panfil: Industrial Physics and Simulations                   ##
# http://industrialphys.com                                           ##
# THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK           ##
########################################################################
OEXT:=o
BEXT:=x
SHEXT:=so
FPIC:=-fpic
RM:=rm -f
LEXT:=a
LBS:=ar crv 
LM:=-lm -lrt
NOUT:= -o 
MEXT:=mod
#VPATH:=$(ROOTDIR)/bem $(ROOTDIR)/fft $(ROOTDIR)/geom $(ROOTDIR)/interp $(ROOTDIR)/lalg $(ROOTDIR)/ode $(ROOTDIR)/opengl $(ROOTDIR)/utils  $(ROOTDIR)/tst src
F90DIR:=$(ROOTDIR)/f90
CDIR:=$(ROOTDIR)/c
 
vpath %.f90 $(F90DIR) src
vpath %.c   $(CDIR) src
vpath %.h   $(CDIR) src
MKLROOT:=/opt/intel/mkl
MKLCOPT:=-m64 -I$(MKLROOT)/include
MKLCLOPT:=-Wl,--start-group ${MKLROOT}/lib/intel64/libmkl_intel_lp64.a ${MKLROOT}/lib/intel64/libmkl_sequential.a ${MKLROOT}/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm -ldl

#MKLCLOPT:= -L$(MKLROOT)/lib/intel64 -Wl,--no-as-needed -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl
CINC=-I$(CDIR)

