########################################################################
# Shimon Panfil: Industrial Physics and Simulations                   ##
# http://industrialphys.com                                           ##
# THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK           ##
########################################################################
%.$(OEXT): %.f90
	$(FC) -c $(FOPT)    $<  $(NOUT) $@
%.$(BEXT): %.f90
	$(FC) $(FLOPT)  $(NOUT) $@ $^ 
%.$(OEXT): %.c
	$(CC) -c $(COPT)   $< $(NOUT) $@ $(MKLCOPT)
%.$(BEXT): %.c
	$(CC) $(CLOPT)  $(NOUT) $@ $^ $(MKLCLOPT) $(MKLCOPT)



