!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! SHIMON PANFIL: INDUSTRIAL PHYSICS AND SIMULATIONS        !
! HTTP://INDUSTRIALPHYS.COM                                !
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODULE CDATA
USE FDEFS
IMPLICIT NONE
PUBLIC
INTEGER,PARAMETER::I08_LBL=0,F32_LBL=16,F64_LBL=32,C32_LBL=48,C64_LBL=64,I32_LBL=80
TYPE :: CDATA_F32 
    REAL(F32),ALLOCATABLE,DIMENSION(:)::BUF  
    INTEGER::SHP(8)
END TYPE  CDATA_F32 

CONTAINS

SUBROUTINE CLEAN_CDATA_F32(D)
    TYPE(CDATA_F32),INTENT(INOUT) :: D
    IF(ALLOCATED(D%BUF)) DEALLOCATE(D%BUF)
    D%SHP=0
END SUBROUTINE CLEAN_CDATA_F32

SUBROUTINE WRITE_CDATA_F32(D,FNAME,FLAG)
    TYPE(CDATA_F32),INTENT(INOUT):: D
    CHARACTER(*) :: FNAME
    INTEGER :: FLAG
    INTEGER::WRUNITB
    OPEN(NEWUNIT=WRUNITB,FILE=FNAME,ACCESS="STREAM",&
        STATUS="REPLACE",IOSTAT=FLAG)
    IF(FLAG>0) RETURN
    WRITE(WRUNITB) D%SHP
    WRITE(WRUNITB) D%BUF
    CLOSE(WRUNITB)
    FLAG=0
END SUBROUTINE WRITE_CDATA_F32

SUBROUTINE READ_CDATA_F32(D,FNAME,FLAG)
    TYPE(CDATA_F32),INTENT(INOUT):: D    
    CHARACTER(*) :: FNAME
    INTEGER :: FLAG
    INTEGER::RDUNITB,N,I
    OPEN(NEWUNIT=RDUNITB,FILE=FNAME,ACCESS="STREAM",&
        STATUS="OLD",IOSTAT=FLAG)
    IF(FLAG/=0) RETURN
    CALL CLEAN_CDATA_F32(D)
    READ(RDUNITB) D%SHP
    N=1 ! COMPUTE TOTAL SIZE
    DO I=2,8
        N=N*D%SHP(I);
    ENDDO
    ALLOCATE(D%BUF(N),STAT=FLAG)
    IF(FLAG/=0) RETURN
    READ(RDUNITB) D%BUF
    CLOSE(RDUNITB)    
    FLAG=0
END SUBROUTINE READ_CDATA_F32

END MODULE CDATA
