!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Shimon Panfil: Industrial Physics and Simulations                   !!
! http://industrialphys.com                                           !!
! THE SOFTWARE IS PROVIDED "AS IS", USE IT AT YOUR OWN RISK           !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
FUNCTION KP(PHI,T,ALPHA,BETA) RESULT(RES)
    USE FDEFS
    REAL(F32):: ALPHA,BETA,PHI,T,RES

    RES=-(ONE_F32+BETA*COS(ALPHA*T))*SIN(PHI)

ENDFUNCTION KP

SUBROUTINE KP_LP2(RES,NSTEP,NSTRIDE,DT,PHI0,PSI0,T0,ALPHA,BETA)
    USE FDEFS
    IMPLICIT NONE
    REAL(F32)::RES(3,NSTRIDE),DT,PHI0,PSI0,T0,ALPHA,BETA
    INTEGER::NSTEP,NSTRIDE
    REAL(F32)::KP
    INTEGER::I,J
    REAL(F32)::PHIOLD,PSIOLD,PHI,PSI,T,PSI1
    REAL(F32),PARAMETER::PI2=TWO_F32*PI_F32

    PHI=ZERO_F32
    PSI1=ZERO_F32
    PHIOLD=PHI0
    PSIOLD=PSI0+HALF_F32*DT*KP(PHI0,T0,ALPHA,BETA)
    T=T0
    DO I=1,NSTRIDE
        DO J=1,NSTEP
            PHI=PHIOLD+DT*PSIOLD
            IF(PHI.GT.PI_F32) PHI=PHI-PI2
            IF(PHI.LE.-PI_F32) PHI=PHI+PI2
            PSI=PSIOLD+DT*KP(PHI,T,ALPHA,BETA)
            T=T+DT
            PHIOLD=PHI
            PSI1=HALF_F32*(PSIOLD+PSI)
            PSIOLD=PSI
        ENDDO
        RES(1,I)=PHI
        RES(2,I)=PSI1
        RES(3,I)=T
    ENDDO
ENDSUBROUTINE KP_LP2

SUBROUTINE KP_RK4(RES,NSTEP,NSTRIDE,DT,PHI0,PSI0,T0,ALPHA,BETA)
    USE FDEFS
    IMPLICIT NONE
    REAL(F32)::RES(3,NSTRIDE),DT,PHI0,PSI0,T0,ALPHA,BETA
    INTEGER::NSTEP,NSTRIDE
    REAL(F32):: KP
    INTEGER::I,J
    REAL(F32)::PHIOLD,PSIOLD,PHI,PSI,T,PSI1,PSI2,PSI3,PSI4,PHI1,PHI2,PHI3,PHI4
    REAL(F32),PARAMETER::PI2=TWO_F32*PI_F32
    REAL(F32),PARAMETER::SIXTH=ONE_F32/6.0_F32
     PHI=ZERO_F32
    PSI=ZERO_F32
    PHIOLD=PHI0
    PSIOLD=PSI0
    T=T0
    DO I=1,NSTRIDE
        DO J=1,NSTEP
            PSI1=KP(PHIOLD,T,ALPHA,BETA)
            PHI1=PSIOLD
            PSI2=KP(PHIOLD+HALF_F32*PHI1,T+HALF_F32*DT,ALPHA,BETA)
            PHI2=PSIOLD+HALF_F32*PSI1
            PSI3=KP(PHIOLD+HALF_F32*PHI2,T+HALF_F32*DT,ALPHA,BETA)
            PHI3=PSIOLD+HALF_F32*PSI2
            PSI4=KP(PHIOLD+PHI3,T+DT,ALPHA,BETA)
            PHI4=PSIOLD+PSI3
            PHI=PHIOLD+DT*SIXTH*(PHI1+2.0_F32*PHI2+2.0_F32*PHI3+PHI4)
            IF(PHI.GT.PI_F32) PHI=PHI-PI2
            IF(PHI.LE.-PI_F32) PHI=PHI+PI2
            PSI=PSIOLD+DT*SIXTH*(PSI1+2.0_F32*PSI2+2.0_F32*PSI3+PSI4)
            T=T+DT
            PHIOLD=PHI
            PSIOLD=PSI
        ENDDO
        RES(1,I)=PHI
        RES(2,I)=PSI
        RES(3,I)=T
    ENDDO
ENDSUBROUTINE KP_RK4


