!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! Author: Shimon Panfil                                           !
! Copyright (c) Shimon Panfil Industrial Physics and Simulations  !
! http://industrialphys.com                                       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
MODULE IOF_MODULE
    IMPLICIT NONE
    PUBLIC
    INTEGER,PARAMETER :: IN_UNIT_B=11,OUT_UNIT_B=12
    INTEGER :: IOS
    CHARACTER(128):: IOM="OK"
    CONTAINS
SUBROUTINE  READBINT(R,C,A,FILENAME)
    INTEGER,INTENT(INOUT) ::R,C
    INTEGER,ALLOCATABLE,DIMENSION(:,:),INTENT(OUT) ::A
    CHARACTER(32) :: FILENAME
    OPEN(UNIT=IN_UNIT_B,FILE=FILENAME,ACCESS="STREAM",IOSTAT=IOS,IOMSG=IOM,STATUS="OLD")
    IF(IOS>0) THEN
      IOM="CAN'T OPEN FILE: "//FILENAME
      RETURN
    END IF
    READ(IN_UNIT_B) C,R !REVERSED ORDER,ROWS<->COLS
    IF(R<1 .OR. C<1) THEN
      IOM="BAD DIMENSIONS"
      RETURN
    END IF
    ALLOCATE(A(R,C))
    READ(IN_UNIT_B) A
    CLOSE(IN_UNIT_B)
END SUBROUTINE  READBINT       
SUBROUTINE  WRITEBINT(R,C,A,FILENAME)
    INTEGER,INTENT(INOUT) ::R,C
    INTEGER,DIMENSION(:,:),INTENT(IN) ::A
    CHARACTER(32) :: FILENAME
    OPEN(UNIT=OUT_UNIT_B,FILE=FILENAME,ACCESS="STREAM",IOSTAT=IOS,&
           IOMSG=IOM,STATUS="REPLACE")
    IF(IOS>0) THEN
      IOM="CAN'T OPEN FILE: "//FILENAME
      RETURN
    END IF
    WRITE(OUT_UNIT_B) C,R !REVERSED ORDER,ROWS<->COLS
    WRITE(OUT_UNIT_B) A
    CLOSE(OUT_UNIT_B)
END SUBROUTINE WRITEBINT
SUBROUTINE  READBDBL(R,C,A,FILENAME)
    INTEGER,INTENT(INOUT) ::R,C
    REAL(8),ALLOCATABLE,DIMENSION(:,:),INTENT(OUT) ::A
    CHARACTER(32) :: FILENAME
    OPEN(UNIT=IN_UNIT_B,FILE=FILENAME,ACCESS="STREAM",IOSTAT=IOS,IOMSG=IOM,STATUS="OLD")
    IF(IOS>0) THEN
      IOM="CAN'T OPEN FILE: "//FILENAME
      RETURN
    END IF
    READ(IN_UNIT_B) C,R !REVERSED ORDER,ROWS<->COLS
    IF(R<1 .OR. C<1) THEN
      IOM="BAD DIMENSIONS"
      RETURN
    END IF
    ALLOCATE(A(R,C))
    READ(IN_UNIT_B) A
    CLOSE(IN_UNIT_B)
END SUBROUTINE  READBDBL       
SUBROUTINE  WRITEBDBL(R,C,A,FILENAME)
    INTEGER,INTENT(INOUT) ::R,C
    REAL(8),DIMENSION(:,:),INTENT(IN) ::A
    CHARACTER(32) :: FILENAME
    OPEN(UNIT=OUT_UNIT_B,FILE=FILENAME,ACCESS="STREAM",IOSTAT=IOS,&
           IOMSG=IOM,STATUS="REPLACE")
    IF(IOS>0) THEN
      IOM="CAN'T OPEN FILE: "//FILENAME
      RETURN
    END IF
    WRITE(OUT_UNIT_B) C,R !REVERSED ORDER,ROWS<->COLS
    WRITE(OUT_UNIT_B) A
    CLOSE(OUT_UNIT_B)
END SUBROUTINE WRITEBDBL

END MODULE IOF_MODULE



